### ISSUE TITLE
Does this works with asynchronous code, task async/await ?

### ISSUE THREAD

**Issue by Ricky1997** [Vycka/LoadRunner#12]

**Comment by Vycka** [comment]
Hello, sorry for late replay.

You can't use async await in IScenario.ExecuteScenario() directly:

* LoadRunner engine ultimately measures the duration it takes for IScenario.ExecuteScenario() method to complete.
* But doing await inside void return methods (like void ExecuteScenario()) will cause method to complete instantly (as under the hood await registers the callback to the rest of the code block).

For workaround: One can just use task.Result approach instead of await.
E.g.
` HttpResponseMessage result = await httpclient.ExecuteAsync()`
vs
` HttpResponseMessage result = httpclient.ExecuteAsync().Result`

**Comment by Ricky1997** [comment]
Hi,

I want to know.that how is the tps value different from no. Of iterations/
time dimension.

How are total transactions calculated in one sec ?

Regards
Ricky

**Comment by Vycka** [comment]
Hello, Transactions per Second metric it-self is straight forward. For iterations received it tracks:
https://github.com/Vycka/LoadRunner/blob/master/src/Viki.LoadRunner.Engine/Aggregators/Metrics/TransactionsPerSecMetric.cs#L32
 * Count of successful iterations 
 * Timestamp of earliest started iteration.
 * Timestamp of latest ended iteration.
Thus final formula happens to be` Successful_iteration_count / (Latest_iteration_ended_seconds - Earliest_iteration_started_seconds)`

Metrics don't know anything about used dimensions in aggregation:
* Dimensions group iterations in advance and for each group(row) it spawns new set of metric instances to calculate result.
* Lets say we had a "Demo" load-test which in total had 6 Iterations (all successful):

| Request Id | Iteration started T+s | Iteration Ended  T+s |
------------- | -------- | ----------------------
| 0 | 0 | 1 |
| 1 | 1 | 1 |
| 2 | 1 | 2 |
| 3 | 3 | 5 |
| 4 | 4 | 5 |
| 5 | 5 | 6 |

### If we only had KPI aggregation (no dimensions)
```
new HistogramAggregator()
    .Add(new TransactionsPerSecMetric());
```
All 6 iterations would be calculated into single TPS value: 6 / (6-0) = 1


### But when we combine it with dimensions:
```
new HistogramAggregator()
    .Add(new TimeDimension(TimeSpan.FromSeconds(3)))
    .Add(new TransactionsPerSecMetric());
```

By default TimeDimension groups by Iteration Ended value 
https://github.com/Vycka/LoadRunner/blob/master/src/Viki.LoadRunner.Engine/Aggregators/Dimensions/TimeDimension.cs#L15
As result of it, data gets broken into 3 slices

* 1st group

| Request Id | Iteration started T+s | Iteration Ended  T+s |
------------- | -------- | ----------------------
| 0 | 0 | 1 |
| 1 | 1 | 1 |
| 2 | 1 | 2 |

TPS = 3 / (2 - 0) = 1.5

* 2nd group

| Request Id | Iteration started T+s | Iteration Ended  T+s |
------------- | -------- | ----------------------
| 3 | 3 | 5 |
| 4 | 4 | 5 |

TPS = 2 / (5 - 3) = 1

* 3rd group

| Request Id | Iteration started T+s | Iteration Ended  T+s |
------------- | -------- | ----------------------
| 5 | 5 | 6 |

TPS = 1 / (6 - 5) = 1


As result of such math - TPS results are not 100% accurate, but difference is negligible if enough iterations are made within one group

**Comment by Vycka** [comment]
Given no additional comments, I assume that previous answer was sufficient.
