### ISSUE TITLE
Need release nuget

### ISSUE THREAD

**Issue by Ricky1997** [Vycka/LoadRunner#13]
I am using this package for load testing in my project. Although I cant deploy my project as nuget because the nuget you have released are in pre release mode.

Can you create a latest nuget which is ready to be released ?

**Comment by Vycka** [comment]
Sure, didn't though that such limitation might exist on some CI.

Packages built & published:
https://www.nuget.org/packages/Viki.LoadRunner/0.8.83
https://www.nuget.org/packages/Viki.LoadRunner.Tools/0.8.49

Sorry for inconvenience caused by me not not noticing new issue.
